### ISSUE TITLE
Errors on Retrieve Users

### ISSUE THREAD

**Issue by tdswellington** [santoshCRM/RoleReplicator#3]
Hello,
recently updated XRM Toolbox to v1.2019.6.33. Since then, Role Replicator gives the following error:

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.InvalidCastException: Unable to cast object of type 'Microsoft.Xrm.Tooling.Connector.CrmServiceClient' to type 'Microsoft.Xrm.Sdk.Client.OrganizationServiceProxy'.
   at RoleReplicatorControl.Helper.createConn(IOrganizationService Service)
   at RoleReplicatorControl.RoleReplicator.btn_retUsers_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by santoshCRM** [comment]
Plugin is update now. 1.2019.11.20 is new version
